"""add departments, student_classes, and department_id fields

Revision ID: 779eea438441
Revises: 6c69347a84fc
Create Date: 2026-07-26 18:14:17.336837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779eea438441'
down_revision: Union[str, Sequence[str], None] = '6c69347a84fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('student_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', name='uq_student_class')
    )
    op.create_index(op.f('ix_student_classes_id'), 'student_classes', ['id'], unique=False)
    op.drop_constraint(op.f('uq_attendance_session_student'), 'attendance', type_='unique')
    op.add_column('classes', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'departments', ['department_id'], ['id'])
    op.add_column('students', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'department_id')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'department_id')
    op.create_unique_constraint(op.f('uq_attendance_session_student'), 'attendance', ['session_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_student_classes_id'), table_name='student_classes')
    op.drop_table('student_classes')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
