"""add department_id to teachers

Revision ID: da651f0d550d
Revises: 779eea438441
Create Date: 2026-08-05 10:15:50.400475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da651f0d550d'
down_revision: Union[str, Sequence[str], None] = '779eea438441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'department_id')
    # ### end Alembic commands ###
