"""add student profile and photo fields

Revision ID: db5fe682d605
Revises: 6c69347a84fc
Create Date: 2026-07-17 13:02:08.863979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5fe682d605'
down_revision: Union[str, Sequence[str], None] = '6c69347a84fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attendance_session_student'), 'attendance', type_='unique')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('roll_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('semester', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_straight_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_left_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_right_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_roll_number'), 'users', ['roll_number'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_roll_number'), table_name='users')
    op.drop_column('users', 'photo_right_path')
    op.drop_column('users', 'photo_left_path')
    op.drop_column('users', 'photo_straight_path')
    op.drop_column('users', 'department')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'roll_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.create_unique_constraint(op.f('uq_attendance_session_student'), 'attendance', ['session_id', 'student_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
